#ddev-generated
hooks:
  post-start:
    - exec: >
        if [ "$DATABASE" = "sqlite" ]; then
          if [ ! -f database/database.sqlite ]; then
            touch database/database.sqlite;
          fi
        fi
    - exec: >
        if [ ! -d vendor ]; then
          composer install;
          php artisan migrate;
        fi